-- Table: public.availability

-- DROP TABLE IF EXISTS public.availability;

CREATE TABLE IF NOT EXISTS public.availability
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    car_id bigint,
    location_id bigint,
    status boolean DEFAULT true,
    CONSTRAINT availability_pkey PRIMARY KEY (id),
    CONSTRAINT availability_car_id_fkey FOREIGN KEY (car_id)
        REFERENCES public.cars (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT availability_location_id_fkey FOREIGN KEY (location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.availability
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.availability TO anon;

GRANT ALL ON TABLE public.availability TO postgres;

GRANT ALL ON TABLE public.availability TO supabase_admin;

GRANT ALL ON TABLE public.availability TO authenticated;

GRANT ALL ON TABLE public.availability TO service_role;