-- Table: public.bookings

-- DROP TABLE IF EXISTS public.bookings;

CREATE TABLE IF NOT EXISTS public.bookings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    car_id bigint,
    person_id bigint,
    pick_up_date date,
    pick_up_time time without time zone,
    pick_up_location_id bigint,
    drop_off_date date,
    drop_off_time time without time zone,
    drop_off_location_id bigint,
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    CONSTRAINT bookings_car_id_fkey FOREIGN KEY (car_id)
        REFERENCES public.cars (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bookings_drop_off_location_id_fkey FOREIGN KEY (drop_off_location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bookings_person_id_fkey FOREIGN KEY (person_id)
        REFERENCES public.persons (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bookings_pick_up_location_id_fkey FOREIGN KEY (pick_up_location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bookings
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.bookings TO anon;

GRANT ALL ON TABLE public.bookings TO postgres;

GRANT ALL ON TABLE public.bookings TO supabase_admin;

GRANT ALL ON TABLE public.bookings TO authenticated;

GRANT ALL ON TABLE public.bookings TO service_role;