-- Table: public.cars_models

-- DROP TABLE IF EXISTS public.cars_models;

CREATE TABLE IF NOT EXISTS public.cars_models
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    seating_capacity smallint,
    img_url text COLLATE pg_catalog."default",
    tank_capacity real,
    mode text COLLATE pg_catalog."default",
    price real,
    discounted_price real,
    CONSTRAINT cars_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cars_models
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.cars_models TO anon;

GRANT ALL ON TABLE public.cars_models TO postgres;

GRANT ALL ON TABLE public.cars_models TO supabase_admin;

GRANT ALL ON TABLE public.cars_models TO authenticated;

GRANT ALL ON TABLE public.cars_models TO service_role;