-- Table: public.cars

-- DROP TABLE IF EXISTS public.cars;

CREATE TABLE IF NOT EXISTS public.cars
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    plate_number text COLLATE pg_catalog."default",
    car_model_id bigint,
    purchase_date date,
    rate smallint,
    CONSTRAINT cars_pkey1 PRIMARY KEY (id),
    CONSTRAINT cars_car_model_id_fkey FOREIGN KEY (car_model_id)
        REFERENCES public.cars_models (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cars
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.cars TO anon;

GRANT ALL ON TABLE public.cars TO postgres;

GRANT ALL ON TABLE public.cars TO supabase_admin;

GRANT ALL ON TABLE public.cars TO authenticated;

GRANT ALL ON TABLE public.cars TO service_role;