-- Table: public.locations

-- DROP TABLE IF EXISTS public.locations;

CREATE TABLE IF NOT EXISTS public.locations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default",
    coordinates text COLLATE pg_catalog."default",
    CONSTRAINT locations_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.locations
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.locations TO anon;

GRANT ALL ON TABLE public.locations TO postgres;

GRANT ALL ON TABLE public.locations TO supabase_admin;

GRANT ALL ON TABLE public.locations TO authenticated;

GRANT ALL ON TABLE public.locations TO service_role;