-- Table: public.persons

-- DROP TABLE IF EXISTS public.persons;

CREATE TABLE IF NOT EXISTS public.persons
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default",
    mobile_number text COLLATE pg_catalog."default",
    place text COLLATE pg_catalog."default",
    CONSTRAINT persons_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.persons
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.persons TO anon;

GRANT ALL ON TABLE public.persons TO postgres;

GRANT ALL ON TABLE public.persons TO supabase_admin;

GRANT ALL ON TABLE public.persons TO authenticated;

GRANT ALL ON TABLE public.persons TO service_role;